In [1]:
import sys
import os
import pandas as pd
import scanpy as sc
from mudata import MuData
import muon as mu
import numpy as np

pd.set_option('display.max_columns', 100)
# os.chdir('/data1/liyuzhe/Ref/cpdb')

2026-03-19 10:32:38.689878: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-03-19 10:32:38.748047: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-03-19 10:32:39.667587: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [2]:
print(sys.version)

3.8.5 (default, Sep  4 2020, 07:30:14)
[GCC 7.3.0]

In [3]:
# figure settings
sc.settings.set_figure_params(dpi=200, frameon=False)
sc.set_figure_params(dpi=200, facecolor="white")
sc.set_figure_params(figsize=(5, 5))

# Run statistical analysis

In [4]:
cpdb_file_path = '/data1/liyuzhe/Ref/cpdb/v4.1.0/cellphonedb.zip'
meta_file_path = 'data/metadata.tsv'
counts_file_path = 'data/normalised_log_counts.h5ad'
# microenvs_file_path = 'data/microenvironment.tsv'
out_path = 'results/method2'

In [5]:
from cellphonedb.src.core.methods import cpdb_statistical_analysis_method

deconvoluted, means, pvalues, significant_means = cpdb_statistical_analysis_method.call(
    cpdb_file_path = cpdb_file_path,                 # mandatory: CellPhoneDB database zip file.
    meta_file_path = meta_file_path,                 # mandatory: tsv file defining barcodes to cell label.
    counts_file_path = counts_file_path,             # mandatory: normalized count matrix.
    counts_data = 'hgnc_symbol',                     # defines the gene annotation in counts matrix.
    # microenvs_file_path = microenvs_file_path,       # optional (default: None): defines cells per microenvironment.
    iterations = 1000,                               # denotes the number of shufflings performed in the analysis.
    threshold = 0.1,                                 # defines the min % of cells expressing a gene for this to be employed in the analysis.
    threads = 8,                                     # number of threads to use in the analysis.
    debug_seed = 42,                                 # debug randome seed. To disable >=0.
    result_precision = 3,                            # Sets the rounding for the mean values in significan_means.
    pvalue = 0.05,                                   # P-value threshold to employ for significance.
    subsampling = False,                             # To enable subsampling the data (geometri sketching).
    subsampling_log = False,                         # (mandatory) enable subsampling log1p for non log-transformed data inputs.
    subsampling_num_pc = 100,                        # Number of componets to subsample via geometric skectching (dafault: 100).
    subsampling_num_cells = 1000,                    # Number of cells to subsample (integer) (default: 1/3 of the dataset).
    separator = '|',                                 # Sets the string to employ to separate cells in the results dataframes "cellA|CellB".
    debug = False,                                   # Saves all intermediate tables employed during the analysis in pkl format.
    output_path = out_path,                          # Path to save results.
    output_suffix = None                             # Replaces the timestamp in the output files by a user defined string in the  (default: None).
    )

Reading user files...
The following user files were loaded successfully:
data/normalised_log_counts.h5ad
data/metadata.tsv
[ ][CORE][19/03/26-10:32:51][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:42 Threads:8 Precision:3
[ ][CORE][19/03/26-10:32:51][WARNING] Debug random seed enabled. Set to 42
[ ][CORE][19/03/26-10:33:02][INFO] Running Real Analysis
[ ][CORE][19/03/26-10:33:02][INFO] Running Statistical Analysis

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1000/1000 [27:31<00:00,  1.65s/it]

[ ][CORE][19/03/26-11:00:35][INFO] Building Pvalues result
[ ][CORE][19/03/26-11:00:36][INFO] Building results
Saved deconvoluted to results/method2/statistical_analysis_deconvoluted_03_19_2026_11:00:36.txt
Saved means to results/method2/statistical_analysis_means_03_19_2026_11:00:36.txt
Saved pvalues to results/method2/statistical_analysis_pvalues_03_19_2026_11:00:36.txt
Saved significant_means to results/method2/statistical_analysis_significant_means_03_19_2026_11:00:36.txt

In [6]:
pvalues.head(3)

,id_cp_interaction,interacting_pair,partner_a,partner_b,gene_a,gene_b,secreted,receptor_a,receptor_b,annotation_strategy,is_integrin,Group3|Group3,Group3|Group4,Group3|Lymphocyte,Group3|Macrophage_01_CD44,Group3|Macrophage_02_FLT1,Group3|Macrophage_03_FYN,Group3|Microglia_01_P2RY12,Group3|Microglia_02_DNAJB1,Group3|Microglia_03_IGF2R,Group3|Microglia_04_ITGAX,Group3|Microglia_05_KLF2,Group3|Microglia_06_IL1B,Group3|Microglia_07_MKI67,Group3|SHH,Group4|Group3,Group4|Group4,Group4|Lymphocyte,Group4|Macrophage_01_CD44,Group4|Macrophage_02_FLT1,Group4|Macrophage_03_FYN,Group4|Microglia_01_P2RY12,Group4|Microglia_02_DNAJB1,Group4|Microglia_03_IGF2R,Group4|Microglia_04_ITGAX,Group4|Microglia_05_KLF2,Group4|Microglia_06_IL1B,Group4|Microglia_07_MKI67,Group4|SHH,Lymphocyte|Group3,Lymphocyte|Group4,Lymphocyte|Lymphocyte,Lymphocyte|Macrophage_01_CD44,Lymphocyte|Macrophage_02_FLT1,Lymphocyte|Macrophage_03_FYN,Lymphocyte|Microglia_01_P2RY12,Lymphocyte|Microglia_02_DNAJB1,Lymphocyte|Microglia_03_IGF2R,Lymphocyte|Microglia_04_ITGAX,Lymphocyte|Microglia_05_KLF2,...,Microglia_05_KLF2|Microglia_01_P2RY12,Microglia_05_KLF2|Microglia_02_DNAJB1,Microglia_05_KLF2|Microglia_03_IGF2R,Microglia_05_KLF2|Microglia_04_ITGAX,Microglia_05_KLF2|Microglia_05_KLF2,Microglia_05_KLF2|Microglia_06_IL1B,Microglia_05_KLF2|Microglia_07_MKI67,Microglia_05_KLF2|SHH,Microglia_06_IL1B|Group3,Microglia_06_IL1B|Group4,Microglia_06_IL1B|Lymphocyte,Microglia_06_IL1B|Macrophage_01_CD44,Microglia_06_IL1B|Macrophage_02_FLT1,Microglia_06_IL1B|Macrophage_03_FYN,Microglia_06_IL1B|Microglia_01_P2RY12,Microglia_06_IL1B|Microglia_02_DNAJB1,Microglia_06_IL1B|Microglia_03_IGF2R,Microglia_06_IL1B|Microglia_04_ITGAX,Microglia_06_IL1B|Microglia_05_KLF2,Microglia_06_IL1B|Microglia_06_IL1B,Microglia_06_IL1B|Microglia_07_MKI67,Microglia_06_IL1B|SHH,Microglia_07_MKI67|Group3,Microglia_07_MKI67|Group4,Microglia_07_MKI67|Lymphocyte,Microglia_07_MKI67|Macrophage_01_CD44,Microglia_07_MKI67|Macrophage_02_FLT1,Microglia_07_MKI67|Macrophage_03_FYN,Microglia_07_MKI67|Microglia_01_P2RY12,Microglia_07_MKI67|Microglia_02_DNAJB1,Microglia_07_MKI67|Microglia_03_IGF2R,Microglia_07_MKI67|Microglia_04_ITGAX,Microglia_07_MKI67|Microglia_05_KLF2,Microglia_07_MKI67|Microglia_06_IL1B,Microglia_07_MKI67|Microglia_07_MKI67,Microglia_07_MKI67|SHH,SHH|Group3,SHH|Group4,SHH|Lymphocyte,SHH|Macrophage_01_CD44,SHH|Macrophage_02_FLT1,SHH|Macrophage_03_FYN,SHH|Microglia_01_P2RY12,SHH|Microglia_02_DNAJB1,SHH|Microglia_03_IGF2R,SHH|Microglia_04_ITGAX,SHH|Microglia_05_KLF2,SHH|Microglia_06_IL1B,SHH|Microglia_07_MKI67,SHH|SHH
0,CPI-CS0A5B6BD7A,12oxoLeukotrieneB4_byPTGR1_LTB4R,complex:12oxoLeukotrieneB4_byPTGR1,simple:Q15722,NaN,LTB4R,True,False,True,curated,False,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,CPI-CS047D9C0D7,LeukotrieneB4_byLTA4H_LTB4R,complex:LeukotrieneB4_byLTA4H,simple:Q15722,NaN,LTB4R,True,False,True,curated,False,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2,CPI-CS04A56D5BE,12oxoLeukotrieneB4_byPTGR1_LTB4R2,complex:12oxoLeukotrieneB4_byPTGR1,simple:Q9NPC1,NaN,LTB4R2,True,False,True,curated,False,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [7]:
deconvoluted.head(3)

,gene_name,uniprot,is_complex,protein_name,complex_name,id_cp_interaction,Group3,Group4,Lymphocyte,Macrophage_01_CD44,Macrophage_02_FLT1,Macrophage_03_FYN,Microglia_01_P2RY12,Microglia_02_DNAJB1,Microglia_03_IGF2R,Microglia_04_ITGAX,Microglia_05_KLF2,Microglia_06_IL1B,Microglia_07_MKI67,SHH
gene,,,,,,,,,,,,,,,,,,,,
UBASH3B,UBASH3B,Q8TF42,True,UBS3B_HUMAN,Dehydroepiandrosterone_bySTS,CPI-CS09B8977D7,0.062,0.099,0.412,0.837,1.776,0.474,0.418,0.34,0.84,0.768,1.142,0.942,0.52,0.187
UBASH3B,UBASH3B,Q8TF42,True,UBS3B_HUMAN,Dehydroepiandrosterone_bySTS,CPI-CS05760BB78,0.062,0.099,0.412,0.837,1.776,0.474,0.418,0.34,0.84,0.768,1.142,0.942,0.52,0.187
UBASH3B,UBASH3B,Q8TF42,True,UBS3B_HUMAN,Dehydroepiandrosterone_bySTS,CPI-CS0259A0EB4,0.062,0.099,0.412,0.837,1.776,0.474,0.418,0.34,0.84,0.768,1.142,0.942,0.52,0.187

In [8]:
means.head(3)

,id_cp_interaction,interacting_pair,partner_a,partner_b,gene_a,gene_b,secreted,receptor_a,receptor_b,annotation_strategy,is_integrin,Group3|Group3,Group3|Group4,Group3|Lymphocyte,Group3|Macrophage_01_CD44,Group3|Macrophage_02_FLT1,Group3|Macrophage_03_FYN,Group3|Microglia_01_P2RY12,Group3|Microglia_02_DNAJB1,Group3|Microglia_03_IGF2R,Group3|Microglia_04_ITGAX,Group3|Microglia_05_KLF2,Group3|Microglia_06_IL1B,Group3|Microglia_07_MKI67,Group3|SHH,Group4|Group3,Group4|Group4,Group4|Lymphocyte,Group4|Macrophage_01_CD44,Group4|Macrophage_02_FLT1,Group4|Macrophage_03_FYN,Group4|Microglia_01_P2RY12,Group4|Microglia_02_DNAJB1,Group4|Microglia_03_IGF2R,Group4|Microglia_04_ITGAX,Group4|Microglia_05_KLF2,Group4|Microglia_06_IL1B,Group4|Microglia_07_MKI67,Group4|SHH,Lymphocyte|Group3,Lymphocyte|Group4,Lymphocyte|Lymphocyte,Lymphocyte|Macrophage_01_CD44,Lymphocyte|Macrophage_02_FLT1,Lymphocyte|Macrophage_03_FYN,Lymphocyte|Microglia_01_P2RY12,Lymphocyte|Microglia_02_DNAJB1,Lymphocyte|Microglia_03_IGF2R,Lymphocyte|Microglia_04_ITGAX,Lymphocyte|Microglia_05_KLF2,...,Microglia_05_KLF2|Microglia_01_P2RY12,Microglia_05_KLF2|Microglia_02_DNAJB1,Microglia_05_KLF2|Microglia_03_IGF2R,Microglia_05_KLF2|Microglia_04_ITGAX,Microglia_05_KLF2|Microglia_05_KLF2,Microglia_05_KLF2|Microglia_06_IL1B,Microglia_05_KLF2|Microglia_07_MKI67,Microglia_05_KLF2|SHH,Microglia_06_IL1B|Group3,Microglia_06_IL1B|Group4,Microglia_06_IL1B|Lymphocyte,Microglia_06_IL1B|Macrophage_01_CD44,Microglia_06_IL1B|Macrophage_02_FLT1,Microglia_06_IL1B|Macrophage_03_FYN,Microglia_06_IL1B|Microglia_01_P2RY12,Microglia_06_IL1B|Microglia_02_DNAJB1,Microglia_06_IL1B|Microglia_03_IGF2R,Microglia_06_IL1B|Microglia_04_ITGAX,Microglia_06_IL1B|Microglia_05_KLF2,Microglia_06_IL1B|Microglia_06_IL1B,Microglia_06_IL1B|Microglia_07_MKI67,Microglia_06_IL1B|SHH,Microglia_07_MKI67|Group3,Microglia_07_MKI67|Group4,Microglia_07_MKI67|Lymphocyte,Microglia_07_MKI67|Macrophage_01_CD44,Microglia_07_MKI67|Macrophage_02_FLT1,Microglia_07_MKI67|Macrophage_03_FYN,Microglia_07_MKI67|Microglia_01_P2RY12,Microglia_07_MKI67|Microglia_02_DNAJB1,Microglia_07_MKI67|Microglia_03_IGF2R,Microglia_07_MKI67|Microglia_04_ITGAX,Microglia_07_MKI67|Microglia_05_KLF2,Microglia_07_MKI67|Microglia_06_IL1B,Microglia_07_MKI67|Microglia_07_MKI67,Microglia_07_MKI67|SHH,SHH|Group3,SHH|Group4,SHH|Lymphocyte,SHH|Macrophage_01_CD44,SHH|Macrophage_02_FLT1,SHH|Macrophage_03_FYN,SHH|Microglia_01_P2RY12,SHH|Microglia_02_DNAJB1,SHH|Microglia_03_IGF2R,SHH|Microglia_04_ITGAX,SHH|Microglia_05_KLF2,SHH|Microglia_06_IL1B,SHH|Microglia_07_MKI67,SHH|SHH
0,CPI-CS0A5B6BD7A,12oxoLeukotrieneB4_byPTGR1_LTB4R,complex:12oxoLeukotrieneB4_byPTGR1,simple:Q15722,NaN,LTB4R,True,False,True,curated,False,0.112,0.100,0.128,0.118,0.107,0.186,0.108,0.098,0.131,0.094,0.128,0.114,0.153,0.126,0.101,0.089,0.117,0.107,0.096,0.174,0.097,0.087,0.120,0.082,0.117,0.102,0.142,0.115,0.037,0.026,0.054,0.043,0.033,0.111,0.033,0.023,0.056,0.019,0.053,...,0.051,0.041,0.074,0.036,0.071,0.056,0.096,0.069,0.048,0.037,0.065,0.054,0.044,0.122,0.044,0.034,0.067,0.030,0.064,0.050,0.089,0.063,0.082,0.071,0.099,0.089,0.078,0.156,0.078,0.068,0.101,0.064,0.099,0.084,0.123,0.097,0.076,0.064,0.092,0.082,0.072,0.150,0.072,0.062,0.095,0.058,0.092,0.078,0.117,0.090
1,CPI-CS047D9C0D7,LeukotrieneB4_byLTA4H_LTB4R,complex:LeukotrieneB4_byLTA4H,simple:Q15722,NaN,LTB4R,True,False,True,curated,False,0.100,0.089,0.117,0.106,0.096,0.174,0.096,0.086,0.119,0.082,0.116,0.102,0.141,0.115,0.087,0.076,0.104,0.093,0.083,0.161,0.083,0.073,0.106,0.069,0.103,0.089,0.128,0.102,0.060,0.048,0.076,0.066,0.055,0.133,0.056,0.045,0.078,0.041,0.076,...,0.052,0.042,0.075,0.038,0.072,0.058,0.097,0.071,0.050,0.038,0.066,0.056,0.045,0.123,0.046,0.036,0.069,0.031,0.066,0.052,0.091,0.064,0.084,0.072,0.100,0.090,0.079,0.157,0.080,0.069,0.103,0.065,0.100,0.085,0.125,0.098,0.113,0.101,0.129,0.119,0.108,0.186,0.109,0.098,0.132,0.094,0.129,0.114,0.154,0.127
2,CPI-CS04A56D5BE,12oxoLeukotrieneB4_byPTGR1_LTB4R2,complex:12oxoLeukotrieneB4_byPTGR1,simple:Q9NPC1,NaN,LTB4R2,True,False,True,curated,False,0.081,0.080,0.085,0.081,0.082,0.103,0.080,0.079,0.078,0.078,0.088,0.081,0.078,0.089,0.070,0.069,0.074,0.070,0.070,0.092,0.069,0.068,0.067,0.067,0.077,0.070,0.067,0.078,0.007,0.005,0.010,0.006,0.007,0.028,0.005,0.004,0.003,0.004,0.013,...,0.023,0.022,0.021,0.021,0.031,0.024,0.021,0.032,0.018,0.016,0.021,0.017,0.018,0.039,0.016,0.015,0.014,0.015,0.024,0.018,0.014,0.025,0.052,0.050,0.056,0.051,0.052,0.073,0.050,0.050,0.048,0.049,0.058,0.052,0.049,0.059,0.045,0.044,0.049,0.045,0.046,0.067,0.044,0.043,0.042,0.043,0.052,0.046,0.042,0.053

In [9]:
significant_means.head(3)

,id_cp_interaction,interacting_pair,partner_a,partner_b,gene_a,gene_b,secreted,receptor_a,receptor_b,annotation_strategy,is_integrin,rank,Group3|Group3,Group3|Group4,Group3|Lymphocyte,Group3|Macrophage_01_CD44,Group3|Macrophage_02_FLT1,Group3|Macrophage_03_FYN,Group3|Microglia_01_P2RY12,Group3|Microglia_02_DNAJB1,Group3|Microglia_03_IGF2R,Group3|Microglia_04_ITGAX,Group3|Microglia_05_KLF2,Group3|Microglia_06_IL1B,Group3|Microglia_07_MKI67,Group3|SHH,Group4|Group3,Group4|Group4,Group4|Lymphocyte,Group4|Macrophage_01_CD44,Group4|Macrophage_02_FLT1,Group4|Macrophage_03_FYN,Group4|Microglia_01_P2RY12,Group4|Microglia_02_DNAJB1,Group4|Microglia_03_IGF2R,Group4|Microglia_04_ITGAX,Group4|Microglia_05_KLF2,Group4|Microglia_06_IL1B,Group4|Microglia_07_MKI67,Group4|SHH,Lymphocyte|Group3,Lymphocyte|Group4,Lymphocyte|Lymphocyte,Lymphocyte|Macrophage_01_CD44,Lymphocyte|Macrophage_02_FLT1,Lymphocyte|Macrophage_03_FYN,Lymphocyte|Microglia_01_P2RY12,Lymphocyte|Microglia_02_DNAJB1,Lymphocyte|Microglia_03_IGF2R,Lymphocyte|Microglia_04_ITGAX,...,Microglia_05_KLF2|Microglia_01_P2RY12,Microglia_05_KLF2|Microglia_02_DNAJB1,Microglia_05_KLF2|Microglia_03_IGF2R,Microglia_05_KLF2|Microglia_04_ITGAX,Microglia_05_KLF2|Microglia_05_KLF2,Microglia_05_KLF2|Microglia_06_IL1B,Microglia_05_KLF2|Microglia_07_MKI67,Microglia_05_KLF2|SHH,Microglia_06_IL1B|Group3,Microglia_06_IL1B|Group4,Microglia_06_IL1B|Lymphocyte,Microglia_06_IL1B|Macrophage_01_CD44,Microglia_06_IL1B|Macrophage_02_FLT1,Microglia_06_IL1B|Macrophage_03_FYN,Microglia_06_IL1B|Microglia_01_P2RY12,Microglia_06_IL1B|Microglia_02_DNAJB1,Microglia_06_IL1B|Microglia_03_IGF2R,Microglia_06_IL1B|Microglia_04_ITGAX,Microglia_06_IL1B|Microglia_05_KLF2,Microglia_06_IL1B|Microglia_06_IL1B,Microglia_06_IL1B|Microglia_07_MKI67,Microglia_06_IL1B|SHH,Microglia_07_MKI67|Group3,Microglia_07_MKI67|Group4,Microglia_07_MKI67|Lymphocyte,Microglia_07_MKI67|Macrophage_01_CD44,Microglia_07_MKI67|Macrophage_02_FLT1,Microglia_07_MKI67|Macrophage_03_FYN,Microglia_07_MKI67|Microglia_01_P2RY12,Microglia_07_MKI67|Microglia_02_DNAJB1,Microglia_07_MKI67|Microglia_03_IGF2R,Microglia_07_MKI67|Microglia_04_ITGAX,Microglia_07_MKI67|Microglia_05_KLF2,Microglia_07_MKI67|Microglia_06_IL1B,Microglia_07_MKI67|Microglia_07_MKI67,Microglia_07_MKI67|SHH,SHH|Group3,SHH|Group4,SHH|Lymphocyte,SHH|Macrophage_01_CD44,SHH|Macrophage_02_FLT1,SHH|Macrophage_03_FYN,SHH|Microglia_01_P2RY12,SHH|Microglia_02_DNAJB1,SHH|Microglia_03_IGF2R,SHH|Microglia_04_ITGAX,SHH|Microglia_05_KLF2,SHH|Microglia_06_IL1B,SHH|Microglia_07_MKI67,SHH|SHH
1388,CPI-SS06C20661D,NRXN2_LRRTM4,simple:P58401,simple:Q86VH4,NRXN2,LRRTM4,False,False,False,curated,False,0.005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
342,CPI-SS0BE3D537D,CDH7_CDH7,simple:Q9ULB5,simple:Q9ULB5,CDH7,CDH7,False,False,False,curated,False,0.005,0.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
341,CPI-SS0C53F7672,CDH6_CDH6,simple:P55285,simple:P55285,CDH6,CDH6,False,False,False,curated,False,0.005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN